### ISSUE TITLE
Error: "unknown license"

### ISSUE THREAD

**Issue by giggio** [marcello3d/node-licensecheck#9]
It is throwing, it should simply specify that it not a valid license.

ouput:

````
C:\proj> licensecheck
C:\Users\giggi\AppData\Roaming\nvm\v5.2.0\node_modules\licensecheck\index.js:170
        throw Error("unknown license: " + JSON.stringify(license))
        ^

Error: unknown license: {"url":"http://opensource.org/licenses/mit-license.php"}
    at Error (native)
    at formatLicense (C:\Users\giggi\AppData\Roaming\nvm\v5.2.0\node_modules\licensecheck\index.js:170:15)
    at Array.map (native)
    at checkPath (C:\Users\giggi\AppData\Roaming\nvm\v5.2.0\node_modules\licensecheck\index.js:209:48)
    at C:\Users\giggi\AppData\Roaming\nvm\v5.2.0\node_modules\licensecheck\index.js:247:19
    at Array.forEach (native)
    at checkPath (C:\Users\giggi\AppData\Roaming\nvm\v5.2.0\node_modules\licensecheck\index.js:246:56)
    at Object.<anonymous> (C:\Users\giggi\AppData\Roaming\nvm\v5.2.0\node_modules\licensecheck\cli.js:52:40)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
````

**Comment by marcello3d** [comment]
You're right—even better would be to support opensource.org urls! :-) Want to make a PR?
